main: lab1.c
	gcc -o output lab1.c
	./output < lab1spr18.a.dat.txt
	./output < lab1spr18.b.dat.txt
	./output < lab1spr18.c.dat.txt

a: lab1.c
	gcc -o output lab1.c
	./output < lab1spr18.a.dat.txt

b: lab1.c
	 gcc -o output lab1.c
	./output < lab1spr18.b.dat.txt

c: lab1.c
	 gcc -o output lab1.c
	./output < lab1spr18.c.dat.txt

d: lab1.c
	gcc -o output lab1.c
	./output < d.dat.txt

clean:
	rm -f *.o a.out
