main: lab2.c
	gcc -o output lab3.c
	./output < lab3spr18.a.dat.txt
	./output < lab3spr18.b.dat.txt
	./output < lab3spr18.c.dat.txt

a: lab3.c
	gcc -o output lab3.c
	./output < lab3spr18.a.dat.txt

b: lab3.c
	 gcc -o output lab3.c
	./output < lab3spr18.b.dat.txt

c: lab3.c
	 gcc -o output lab3.c
	./output < lab3spr18.c.dat.txt

clean:
	rm -f *.o a.out
