main: lab2.c
	gcc -o output lab2.c
	./output < lab2.a.dat.txt
	./output < lab2.b.dat.txt
	./output < lab2.c.dat.txt
	./output < lab2.d.dat.txt

a: lab2.c
	gcc -o output lab2.c
	./output < lab2.a.dat.txt

b: lab2.c
	 gcc -o output lab2.c
	./output < lab2.b.dat.txt

c: lab2.c
	 gcc -o output lab2.c
	./output < lab2.c.dat.txt

d: lab2.c
	gcc -o output lab2.c
	./output < lab2.d.dat.txt

clean:
	rm -f *.o a.out
